version: '3.2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  web:
    build:
      context: "./"
      dockerfile: Dockerfile
      args:
        APP_DIR: "/usr/local/src/aedmap"
        MIX_ENV: "dev"
        PORT: "4000"
        DB_HOST: "db"
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/local/src/aedmap
    links:
      - db:db
